# Copyright (c) eBPF for Windows contributors
# SPDX-License-Identifier: MIT

# This workflow executes a single test, optionally gathering logs and crash dumps.

name: Reusable Test Workflow

on:
  workflow_call:
    inputs:
      name:
        required: true
        type: string
      test_command:
        required: true
        type: string
      build_artifact:
        required: true
        type: string
      environment:
        description: 'Environment to run tests on'
        type: string
        required: true
      gather_dumps:
        required: false
        type: boolean
      pre_test:
        required: false
        type: string
      post_test:
        required: false
        type: string
      configurations:
        required: false
        type: string
        default: '["Debug", "Release"]'

permissions:
  checks: read
  contents: read
  issues: write

jobs:
  run_test:
    timeout-minutes: 60

    strategy:
      matrix:
        configurations: ${{ fromJSON(inputs.configurations) }}
    runs-on: ${{ inputs.environment }}
    env:
      NAME: ${{ inputs.name }}
      BUILD_CONFIGURATION: ${{ matrix.configurations }}
      BUILD_PLATFORM: x64
      TEST_COMMAND: ${{ inputs.test_command }}
      PRE_COMMAND: ${{ inputs.pre_test }}
      POST_COMMAND: ${{ inputs.post_test }}
      DUMP_PATH: c:/dumps/x64/${{ matrix.configurations }}

    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@05e31511f85b41b11d1cf0ef85d0992719546e2c # v2.21.0
      with:
        egress-policy: audit

    - id: skip_check
      uses: fkirc/skip-duplicate-actions@b974a9395958c231af965b70070979a577efa578 # v5.3.2
      with:
        cancel_others: 'false'
        paths_ignore: '["**.md", "**/docs/**"]'

    - name: Configure Windows Error Reporting to make a local copy of any crashes that occur.
      id: configure_windows_error_reporting
      if: (inputs.gather_dumps == true) && (steps.skip_check.outputs.should_skip != 'true')
      run: |
        mkdir ${{ env.DUMP_PATH }}
        New-Item -Path "HKLM:\SOFTWARE\Microsoft\Windows\Windows Error Reporting\LocalDumps" -ErrorAction SilentlyContinue
        New-ItemProperty -Path "HKLM:\SOFTWARE\Microsoft\Windows\Windows Error Reporting\LocalDumps" -Name "DumpType" -Value 2 -PropertyType DWord -ErrorAction SilentlyContinue
        New-ItemProperty -Path "HKLM:\SOFTWARE\Microsoft\Windows\Windows Error Reporting\LocalDumps" -Name "DumpFolder" -Value "${{ env.DUMP_PATH }}" -PropertyType ExpandString -ErrorAction SilentlyContinue

    - name: Download build artifact
      if: steps.skip_check.outputs.should_skip != 'true'
      uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4.3.0
      with:
        name: ${{ inputs.build_artifact }}-${{ matrix.configurations }}
        path: ${{ github.workspace }}

    - name: Extract build artifact
      if: steps.skip_check.outputs.should_skip != 'true'
      working-directory: ${{github.workspace}}
      run: |
        Expand-Archive -Path ${{ github.workspace }}\build-${{ matrix.configurations }}.zip -DestinationPath .\${{ env.BUILD_PLATFORM }}

    - name: Run pre-test command
      if: (inputs.pre_test != '') && (steps.skip_check.outputs.should_skip != 'true')
      id: pre_test
      working-directory: ${{ github.workspace }}\${{ env.BUILD_PLATFORM }}\${{ env.BUILD_CONFIGURATION }}
      run: |
        ${{ env.PRE_COMMAND }}

    - name: Run test
      if: steps.skip_check.outputs.should_skip != 'true'
      id: run_test
      working-directory: ${{ github.workspace }}\${{ env.BUILD_PLATFORM }}\${{ env.BUILD_CONFIGURATION }}
      run: |
        ${{ env.TEST_COMMAND }}

    - name: Run post-test command
      if: always() && (inputs.post_test != '') && (steps.skip_check.outputs.should_skip != 'true')
      id: post_test
      working-directory: ${{ github.workspace }}\${{ env.BUILD_PLATFORM }}\${{ env.BUILD_CONFIGURATION }}
      run: |
        ${{ env.POST_COMMAND }}

    - name: Check for crash dumps
      if: always() && (steps.skip_check.outputs.should_skip != 'true')
      uses: andstor/file-existence-action@558493d6c74bf472d87c84eab196434afc2fa029 # v3.1.0
      id: check_dumps
      with:
        files: ${{ env.DUMP_PATH }}/*.dmp

    - name: Upload any crash dumps
      if: always() && (steps.skip_check.outputs.should_skip != 'true') && (steps.check_dumps.outputs.files_exists == 'true') && (inputs.gather_dumps == true)
      uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
      id: upload_crash_dumps
      with:
        name: Crash-Dumps-${{ env.NAME }}-${{ env.BUILD_PLATFORM }}-${{ env.BUILD_CONFIGURATION }}
        path: ${{ env.DUMP_PATH }}
        retention-days: 5

    - name: Mark run as failed if crash dumps are found
      if: (steps.skip_check.outputs.should_skip != 'true') && (steps.check_dumps.outputs.files_exists == 'true')
      run: exit 1